apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: ap-south-1

vpc:
  subnets:
    private:
      ap-south-1a: { id: subnet-093d16abac042c658 }
      ap-south-1b: { id: subnet-0e05ebcc884ec34b2 }
      ap-south-1c: { id: subnet-032daf90c86d12ead }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
#  - name: ng-2-builders
#    labels: { role: builders }
#    instanceType: t3.small
#    desiredCapacity: 2
#    privateNetworking: true
#    iam:
#      withAddonPolicies:
#        imageBuilder: true
