apiVersion: v1
kind: Service
metadata:
  name: medcare-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: eksmedcareapp
  ports:
    - name: port-loadbalancer
      port: 8081
      targetPort: 8080
      protocol: TCP

